### ISSUE TITLE
IndexOutOfRangeException on iOS?

### ISSUE THREAD

**Issue by drew-512** [timcassell/ProtoPromise#247] opened 2023-06-12 14:36 UTC
The same code that runs without messages or issues on macOS desktop gets a reproducible exception when running under iOS:

```
IndexOutOfRangeException: Index was outside the bounds of the array.
  at Proto.Promises.InternalHelper+InstructionProcessorGroup+InstructionProcessor`1[TYieldInstruction].WaitFor (TYieldInstruction& instruction) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.AwaitUnsafeOnCompleted[TAwaiter,TStateMachine] (TAwaiter& awaiter, TStateMachine& stateMachine) [0x00000] in <00000000000000000000000000000000>:0 
  at Arcspace.AssetService.loadTextureUsingWebRequest[T] (Arcspace.AssetReq`1[T] texReq) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x00000] in <00000000000000000000000000000000>:0 
  at Arcspace.AssetService.loadTextureUsingWebRequest[T] (Arcspace.AssetReq`1[T] texReq) [0x00000] in <00000000000000000000000000000000>:0 
  at Arcspace.AssetService.TryResolveAsset[T] (Arcspace.AssetReq`1[T] req) [0x00000] in <00000000000000000000000000000000>:0 
  at Arcspace.CellScope.TryResolveAsset[T] (Arcspace.AssetReq`1[T] req) [0x00000] in <00000000000000000000000000000000>:0 
```

I'm using v2.5.3 cloned from `main` a few days ago and have no reason this issue is new.  Willing to test earlier versions for regression on request.

Perhaps there is an exception happening from my side that is propagating to `Proto.Promises`?

For reference, here is `loadTextureUsingWebRequest()`:

```.cs
        
        static async void loadTextureUsingWebRequest<T>(AssetReq<T> texReq) where T : UnityEngine.Object {
            var url = texReq.AssetRef.URL;
            using (var req = UnityWebRequestTexture.GetTexture(url, false)) {
                await PromiseYielder.WaitForAsyncOperation(req.SendWebRequest());
                
                if (req.result == UnityWebRequest.Result.Success) {
                    texReq.Resolve(((DownloadHandlerTexture) req.downloadHandler).texture);
                } else {
                    texReq.Fail(req.error);
                }
            }
        }
```

**Comment by drew-512** [comment] 2023-06-12 19:47
Unknown if it worked before since my iOS build is only recently up and running.   If you have a specific tag in mind, I can build against that and see if anything changes.  

Using 2021.3.25.

**Comment by timcassell** [comment] 2023-06-12 19:54
I haven't touched that area of the code since I introduced it, I was just curious if it was ever working. I'll have to look into the cause. iOS bugs are fun...

**Comment by timcassell** [comment] 2023-06-12 20:04
Could you make a simple test case that I can use to repro this? Even if it's flaky, as long as it happens. It could be timing related, or multiple requests running at once related, or something else.

**Comment by timcassell** [comment] 2023-06-12 20:24
I have this check in there to make sure the yield instruction doesn't evaluate more than once per frame.
```cs
if (Time.frameCount != PromiseBehaviour.Instance._currentFrame)
```

Could you see if it makes a difference whether you start the request early in the frame vs late in the frame? If you start a request in `Awake`, `Start`, or `Update`, it's early, if you do a `yield return new WaitForEndOfFrame()`, it's late (and anything in a normal Coroutine could be early or late, depending on whether that Coroutine started before or after the `PromiseYielder`.

**Comment by drew-512** [comment] 2023-06-12 21:11
I dropped in that one line patch and a LOT less errors, but this one emits and appears elsewhere:

```
IndexOutOfRangeException: Index was outside the bounds of the array.
  at Proto.Promises.InternalHelper+InstructionProcessorGroup+InstructionProcessor`1[TYieldInstruction].Evaluate (TYieldInstruction& instruction) [0x00000] in <00000000000000000000000000000000>:0 
  at Proto.Promises.InternalHelper+InstructionProcessorGroup+InstructionProcessor`1[TYieldInstruction].Process () [0x00000] in <00000000000000000000000000000000>:0 
  at Proto.Promises.InternalHelper+PromiseBehaviour+<UpdateRoutine>d__26.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
```

**Comment by timcassell** [comment] 2023-06-12 21:17
I guess I was trying to be too clever... I pushed a fix for that.

**Comment by drew-512** [comment] 2023-06-13 14:56
Would you like me to try your lastest changset?

And yes, you're quite right about on the 60+ requests in flight.  I'm trying to go fast on this project I've been commissioned for (really cool to share about btw), so the focus has been to "just" get a lot of it up and running while also demonstrating multi-platform robustness. 

As often encountered elsewhere, the pattern in particular is loading web-based thumbnails for an item list.  Of course, the longer the list, the more images to fetched and loaded.  Given that how I had things was "short term" until I had more time to do things more responsibly, (a) I'm glad I could help tease out this issue :D and (b) it got me thinking if there is an easy-to-offer and high value idiom that `Proto.Promises` could that would be attractive to your average Unity dev.

What if an `await` in invoked with a flavor (a "class color") such it implies a ceiling number of runners for that flavor.  So for example, a flavor intended for loading 100x50k images would likely to be set for, say, a max of 4 run slots.  

Just offering some brainstorming and naming of a patterns others are also likely to find useful and would find value from in something like `Proto.Promises`.

**Comment by timcassell** [comment] 2023-06-13 15:19
> Would you like me to try your lastest changset?

That would be helpful. It's always good to get real world usage besides just my own unit tests. 😄 

> What if an `await` in invoked with a flavor (a "class color") such it implies a ceiling number of runners for that flavor. So for example, a flavor intended for loading 100x50k images would likely to be set for, say, a max of 4 run slots.

You can already do that with `AsyncSemaphore`.

```cs
private AsyncSemaphore sem = new AsyncSemaphore(4);

public async Promise DownloadTexture(string url)
{
    // Enter the semaphore scope before sending the request, only allows up to 4 simultaneous requests.
    using (await sem.EnterScopeAsync())
    {
        // Normal code here.
    }
}
```

**Comment by drew-512** [comment] 2023-06-13 15:24
Noice!  I'll report on that change and once we're through that I'll try that semaphore approach.  I will restrain from using the eggplant emoji if all goes well.

**Comment by drew-512** [comment] 2023-06-13 18:52
Yay, that latest branch change resolves all issues.  The menu it was loading had about ~100 image loads so not too shabby of field test!

**Comment by timcassell** [comment] 2023-06-13 19:22
Fantastic! Thanks a lot for the report and helping to test the fix! I'll release a new patch version with that fix in soon.

**Closed** 2023-06-13 19:23 UTC
Labels: bug
